### ISSUE TITLE
DC not used in DCCNN

### ISSUE THREAD

**Issue by YuyangXueEd** [hellopipu/HQS-Net#1]
Hi! I went through your code and I found that the implementation of `DCCNN` is not using data consistency layer.

I think maybe in the `forward` you should add this:

```

dcs.append(DCLayer(norm='ortho'))

...


def forward(self, x, k, m):
    for i in range(self.n_iter):
        x_cnn = self.rec_blocks[i](x)
        x += x_cnn
        x = self.update_operation(x, k, m)
        x = self.dcs[i](x, k, m)
```

**Comment by hellopipu** [comment]
hi, thanks for your interest. `self.update_operation()` is a soft dc operation.

**Comment by YuyangXueEd** [comment]
Sure, thank you for your explaination!
